### ISSUE TITLE
EnumerateDistributions doesn't work anymore

### ISSUE THREAD

**Issue by mgurevin** [Biswa96/WslReverse#1]
Hi Biswa,

Looks like the function signature of EnumerateDistributions has been changed, this version of the code doesn't work anymore, at least on my Windows version(10.0.18363).

I just made some changes to comply with the new function signature (I found with OLE viewer): https://github.com/Biswa96/WslReverse/compare/master...mgurevin:master

I'm not gonna a PR because I couldn't find documentation for this hidden API, so don't know which parameters meaning what exactly.

BTW, how did you find the whole naming in the first place?

**Comment by Biswa96** [comment]
Never thought this repository will be used. Thank you for your attention 🤗

But you may know that this repository is a test project and I update the COM vtable according to latest Windows Insider build. According to the README (as of now):

> The COM vtable, used in this project, is according to latest Windows 10 20H1 Insider Preview, that is build 18917 and above.

So, your Windows 10 build is lower than that. You can follow the commit history to find the suitable Windows 10 build as you need. Or use the WslClient COM interface if you have new insider build. _I speculate that it will be documented in future._

**Comment by Biswa96** [comment]
Hope the previous comment answer your question. Feel free to ask any question :)

**Comment by mgurevin** [comment]
thank you for your answer, I reached a person in the WSL team and I decided to use wsl.exe to get the list of installed distributions due to there is no plan for official API.
