### ISSUE TITLE
Please update this project or redirect us to something similar

### ISSUE THREAD

**Issue by derekbsnider** [Biswa96/WslReverse#3]
Not sure why Microsoft is not opening up any APIs other than wslapi.h/wslapi.dll which (for some strange reason) does not provide a way to get a list of distributions, nor to terminate a distribution, even through from what I can tell, wslapi.dll appears to call wsl.exe under the hood, as when first trying to get WslLaunchInteractive() working, I managed to launch a terminal window which had the output of the wsl --help on it, so at least WslLaunchInteractive() uses wsl.exe.

So we need to get smart people like you poking around with this stuff, and keeping open a working interface to those things not offered by wslapi.h -- namely how to get a list of distributions, their current state, and to be able to terminate them as well.

I thought I had things figured out, as the distributions are listed in the registry, and I can find matching wslhost.exe processes running, but curiously enough these processes seem to be placeholders in the windows process list. If you kill them off, WSL keeps running, so WSL.EXE seems to be the only way to get full access to these things.

**Comment by Biswa96** [comment]
This project is just some of my experiments. Can you provide which specific thing you need?

**Comment by derekbsnider** [comment]
Hi Biswa96,

I found your other project which is more up to date -- https://github.com/Biswa96/wslbridge2

All I really need is access to three things which **wslapi.dll** does not provide, but **wsl.exe** does:
- the ability to get the same information that `wsl.exe -l -v` provides
- the ability to terminate a distribution like how `wsl.exe -t <distribution>` does
- the ability to set the default distribution like how `wsl.exe -s <distribution>` does 

I truly do not understand why wslapi.dll does not provide the above three things. I know we can use wsl.exe, but if there is an API available, it should provide the same functionality.

This is the app project I'm working on: https://github.com/derekbsnider/WSLTux

I want to keep an up to date status of the installed distributions, but I don't want to run wsl.exe every few seconds. I'm instead walking the process list looking for **wslhost.exe** processes, but recently found out they are just placeholders, and if I kill them, they disappear, but all the WSL stuff keeps running, so I'd prefer to get access to the same information **wsl.exe** has access to. It would be nice if Microsoft opened the source to it.

**Comment by Biswa96** [comment]
The main problem is that the COM interface is different in multiple Windows version. So, you have to keep track of it. Can you provide which Windows versions you are interested in?

**Comment by derekbsnider** [comment]
Well, WSL is only available in Windows 10 and 11, but I'm guessing that you mean it's also different between different builds? I suppose it would need to work on all builds 1903 and higher. We really need a project to maintain an alternative and complete wslapi.lib until Microsoft releases a complete one.

As it is, their wslapi.h/wslapi.dll offering is not only severely lacking in functionality, it doesn't come with a wslapi.lib, and doesn't quite work according to their own documentation, so they made their own launcher project to show how to use it: https://github.com/microsoft/WSL-DistroLauncher -- and  `WslLaunchInteractive()` doesn't create a process or thread, it blocks on your main process (unlike wsl.exe).

**Comment by Biswa96** [comment]
Understood. I shall try to update those.

**Comment by Biswa96** [comment]
Update. I have figured out the COM interface only for the Windows version as you said. But fixing the whole repository will take some time. Are you using this whole repository or the LxssUserSession interface only?

**Comment by derekbsnider** [comment]
It was only the LxssUserSession I was trying to use, through WslClient's VerboseDistroList() function.

**Comment by Biswa96** [comment]
I have added all the interface versions in one header file. Please check the idl branch https://github.com/Biswa96/WslReverse/tree/idl. It is not ready yet. Feedback is welcomed.
